// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  tutorialSidebar: [

    {
      type: 'category',
      label: 'Matemática Básica',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matematica-basica',
        },
      ],
    },

    {
      type: 'category',
      label: 'Cálculo',
      items: [
        {
          type: 'autogenerated',
          dirName: 'calculo',
        },
      ],
    },

    {
      type: 'category',
      label: 'Física',
      items: [
        {
          type: 'autogenerated',
          dirName: 'fisica',
        },
      ],
    },

  ],
};

export default sidebars;