// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const subjectCategory = (label, dirName, slug) => ({
  type: 'category',
  label,
  collapsed: false,
  link: {
    type: 'generated-index',
    title: label,
    slug,
  },
  items: [
    {
      type: 'autogenerated',
      dirName,
    },
  ],
});

const sidebars = {
  // =========================================================
  // CONTEÚDO
  // =========================================================

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Conteúdo',
      collapsed: false,

      link: {
        type: 'generated-index',
        title: 'Conteúdo',
        description:
          'Explore os conteúdos de Matemática, Cálculo e Física.',
        slug: '/conteudo',
      },

      items: [
        {
          type: 'category',
          label: 'Matemática',

          link: {
            type: 'generated-index',
            title: 'Matemática',
            description:
              'Explore os conteúdos de Matemática, organizados de forma progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'matematica-basica',
            },
          ],
        },

        {
          type: 'category',
          label: 'Cálculo',

          link: {
            type: 'generated-index',
            title: 'Cálculo',
            description:
              'Explore os conteúdos de Cálculo de forma organizada e progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'calculo',
            },
          ],
        },

        {
          type: 'category',
          label: 'Física',

          link: {
            type: 'generated-index',
            title: 'Física',
            description:
              'Explore os conteúdos de Física de forma organizada e progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'fisica',
            },
          ],
        },
      ],
    },
  ],
  // =========================================================
// PREPARAÇÃO
// =========================================================

  preparacaoSidebar: [
    {
      type: 'doc',
      id: 'preparacao/index',
      label: 'Preparação',
    },
  ],
  // =========================================================
  // ENEM
  // =========================================================

  enemSidebar: [
    {
      type: 'category',
      label: 'ENEM',
      collapsed: false,

      link: {
        type: 'doc',
        id: 'preparacao/enem/index',
      },

      items: [
        subjectCategory('Matemática', 'preparacao/enem/matematica', '/preparacao/enem/matematica'),
        subjectCategory('Física', 'preparacao/enem/fisica', '/preparacao/enem/fisica'),
      ],
    },
  ],

  // =========================================================
  // ITA
  // =========================================================

  itaSidebar: [
    {
      type: 'category',
      label: 'ITA',
      collapsed: false,

      link: {
        type: 'doc',
        id: 'preparacao/ita/index',
      },

      items: [
        subjectCategory('Matemática', 'preparacao/ita/matematica', '/preparacao/ita/matematica'),
        subjectCategory('Física', 'preparacao/ita/fisica', '/preparacao/ita/fisica'),
        subjectCategory('Química', 'preparacao/ita/quimica', '/preparacao/ita/quimica'),
      ],
    },
  ],

  // =========================================================
  // IME
  // =========================================================

  imeSidebar: [
    {
      type: 'category',
      label: 'IME',
      collapsed: false,

      link: {
        type: 'doc',
        id: 'preparacao/ime/index',
      },

      items: [
        subjectCategory('Matemática', 'preparacao/ime/matematica', '/preparacao/ime/matematica'),
        subjectCategory('Física', 'preparacao/ime/fisica', '/preparacao/ime/fisica'),
        subjectCategory('Química', 'preparacao/ime/quimica', '/preparacao/ime/quimica'),
      ],
    },
  ],

  // =========================================================
  // OLIMPÍADAS
  // =========================================================

  olimpiadasSidebar: [
    {
      type: 'category',
      label: 'Olimpíadas',
      collapsed: false,

      link: {
        type: 'doc',
        id: 'preparacao/olimpiadas/index',
      },

      items: [
        subjectCategory('Matemática', 'preparacao/olimpiadas/matematica', '/preparacao/olimpiadas/matematica'),
        subjectCategory('Física', 'preparacao/olimpiadas/fisica', '/preparacao/olimpiadas/fisica'),
      ],
    },
  ],
};

export default sidebars;
