// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Conteúdo',
      collapsed: false,

      link: {
        type: 'generated-index',
        title: 'Conteúdo',
        description: 'Explore os conteúdos de Matemática, Cálculo e Física.',
        slug: '/conteudo',
      },

      items: [
        {
          type: 'category',
          label: 'Matemática',

          link: {
            type: 'generated-index',
            title: 'Matemática',
            description:
              'Explore os conteúdos de Matemática, organizados de forma progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'matematica-basica',
            },
          ],
        },

        {
          type: 'category',
          label: 'Cálculo',

          link: {
            type: 'generated-index',
            title: 'Cálculo',
            description:
              'Explore os conteúdos de Cálculo de forma organizada e progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'calculo',
            },
          ],
        },

        {
          type: 'category',
          label: 'Física',

          link: {
            type: 'generated-index',
            title: 'Física',
            description:
              'Explore os conteúdos de Física de forma organizada e progressiva.',
          },

          items: [
            {
              type: 'autogenerated',
              dirName: 'fisica',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;